version: '3.4'
services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: 'id_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3315:3306'
    expose:
      - '3306'
    volumes:
      - id-db:/var/lib/mysql
# Names our volume
volumes:
  id-db: