# Logging holds settings related to api requests logging
[Logging]
    # LoggingEnabled - if this flag is set to true, then if a requests exceeds a threshold or it is unsuccessful, then
    # a log will be printed
    LoggingEnabled = false

    # ThresholdInMicroSeconds represents the maximum duration to consider a request as normal. Above this, if the LoggingEnabled
    # flag is set to true, then a log will be printed
    ThresholdInMicroSeconds = 1000

# API routes configuration
[APIPackages]

[APIPackages.auth]
    Routes = [
        { Name = "/register", Open = true },
        { Name = "/token", Open = true },
    ]
[APIPackages.admin]
    Routes = [
        { Name = "/ping", Open = true },
        { Name = "/createClass", Open = true },
        { Name = "/createProfesor", Open = true },
        { Name = "/setAbsent", Open = true },
        { Name = "/delStudent", Open = true },
        { Name = "/createExam", Open = true },
    ]
[APIPackages.evaluation]
    Routes = [
        { Name = "/getStudentsByClass/:class", Open = true },
        { Name = "/getAllClasses", Open = true },
        { Name = "/addCalificativ", Open = true },
        { Name = "/updateCalificativ", Open = true },
        { Name = "/getCalificative/:student", Open = true },
        { Name = "/getExercitii/:student", Open = true },
    ]
